apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: showcase-dev

resources:
- ../../base

patches:
- path: replicas-patch.yaml
- path: configmap-patch.yaml
images:
- name: backend
  newName: us-central1-docker.pkg.dev/gwsjoseph0326/showcase-dev/backend
  newTag: ee6deab04120
- name: frontend
  newName: us-central1-docker.pkg.dev/gwsjoseph0326/showcase-dev/frontend
  newTag: 7ed86e8f1a23
